### ISSUE TITLE
Error 500 when uploading files

### ISSUE THREAD

**Issue by tobaco** [conclurer/ProcessImageMinimize#3]
In installed a local copy of Processwire 2.4 dev.
when tried to upload some files, the files are saved in the filesystem but disappear from from the page/input mask after saving.

in the console log i get an error 500 with the following response:

> Recoverable Fatal Error: Argument 1 passed to ProcessImageMinimize::getImageIdByPageimage() must be an instance of Pageimage, instance of Pagefile given, called in /Users/tobaco/Documents/pw/cms/site/modules/ProcessImageMinimize/ProcessImageMinimize.module on line 784 and defined (line 158 of /Users/tobaco/Documents/pw/cms/site/modules/ProcessImageMinimize/ProcessImageMinimize.module) This error message was shown because you are using the command line API. Error has been logged.

this happens with images AND with other filetypes.

**Comment by marvinscharle** [comment]
Hi tobaco!

Thank you for submitting this bug. I'd be glad if you could assist me, finding out what went wrong here.

First of all - it looks like you are using the file input field instead of the image input field. Can you verify if you are using the image input field?

Additionally you should mind that **ProcessImageMinimize is only functionally when your site's assets are reachable publicly**, since minimize.pw's servers are fetching the images from your site. Therefore, on localhost, minimize.pw will be unable to fetch your images, so every image minimization process will fail.

Thank you in advance,

Marvin

**Comment by tobaco** [comment]
Hi Marvin,

yes, i was using a file input field, since i wanted to upload some files and no images.
earlier today i had the same problem (upload, but disappear) with language files in the language settings.

it seems like your module will try to work on all upload fields, when the auto minimize all uploads checkbox is set.

the thing with the public reachable images makes sense. will it fail silently?

**Comment by marvinscharle** [comment]
Hi tobaco!

Thank you for your fast response. Ok, that looks definitely like a bug. Can you please add the following line right before line 784 in the ProcessImageMinimize module file and tell me whether or not this solved your issue?

``` php
if (get_class($img) != 'Pageimage') return;
```

The fail happens silently. You will only see it in the database. For more information, please take a look at the [documentation](https://github.com/conclurer/ProcessImageMinimize).

Tank you in advance!

Marvin

**Comment by tobaco** [comment]
Hi Marvin,

this seems to work. Thank you!

Torsten

**Comment by marvinscharle** [comment]
Hi Torsten,

thank you for your help. I've updated ProcessImageMinimize to version 1.0.1 to address your issue. Please make sure to update all your sites.

As a reward for your help, we gift you **500 free image minimizations** on minimize.pw. For this, please send me a message to minimize@conclurer.com with the mail address you registered at minimize.pw.

If you have any additional questions, feel free to contact me at any time.

Thank you!

Marvin
