### ISSUE TITLE
Suddenly Error in Front- and Backend

### ISSUE THREAD

**Issue by tobaco** [conclurer/ProcessImageMinimize#4]
I get suddenly the following error and can't do anything anymore in front- and backend:

> Error: Exception: Duplicate entry '' for key 'minimize_api_reference' (in /is/htdocs/wire/core/Database.php line 114)
> # 0 [internal function]: Database->query('UPDATE process_...')
> # 1
> 
> /is/htdocs/wire/core/DatabaseMysqli.php(35): call_user_func_array(Array, Array)
> # 2 /is/htdocs/site/modules/ProcessImageMinimize/ProcessImageMinimize.module(330): DatabaseMysqli->__call('query', Array)
> # 3 /is/htdocs/site/modules/ProcessImageMinimize/ProcessImageMinimize.module(330): DatabaseMysqli->query('UPDATE process_...')
> # 4 /is/htdocs/site/modules/ProcessImageMinimize/ProcessImageMinimize.module(224): ProcessImageMinimize->getStateFromMinimizeQueue()
> # 5 /is/htdocs/wire/core/Wire.php(381): ProcessImageMinimize->pageLoadedHandler(Object(HookEvent))
> # 6 /is/htdocs/wire/core/Wire.php

what can i do?

**Comment by marvinscharle** [comment]
Hi Torsten,

thank you for the report. We've tracked this issue on a few sites in the last days, therefore we are currently working on a fix. 

Can you please assist me by sending me a dumb of your process_image_minimize database table via mail to minimize@conclurer.com? 

Thanks in advance!

Marvin

**Comment by tobaco** [comment]
Thanks!
I sent you the dump last night.
Is there any quick fix or workaround to get the site running again?

**Comment by marvinscharle** [comment]
Hi Thorsten,

thanks for your help. I pushed a fixed version to the [release candidate branch](https://github.com/conclurer/ProcessImageMinimize/tree/release_candidate). Can you please install this version and tell me if this solved your problem?

Thanks in advance!

Marvin

**Comment by tobaco** [comment]
Hi Marvin,

i updated the module, but no luck. Same errors on new lines:

> Error: Exception: Duplicate entry '' for key 'minimize_api_reference' (in /is/htdocs/wire/core/Database.php line 114)
> 
> #0 [internal function]: Database->query('UPDATE process_...')
> #1 /is/htdocs/wire/core/DatabaseMysqli.php(35): call_user_func_array(Array, Array)
> #2 /is/htdocs/site/modules/ProcessImageMinimize/ProcessImageMinimize.module(334): DatabaseMysqli->__call('query', Array)
> #3 /is/htdocs/site/modules/ProcessImageMinimize/ProcessImageMinimize.module(334): DatabaseMysqli->query('UPDATE process_...')
> #4 /is/htdocs/site/modules/ProcessImageMinimize/ProcessImageMinimize.module(224): ProcessImageMinimize->getStateFromMinimizeQueue()
> #5 /is/htdocs/wire/core/Wire.php(381): ProcessImageMinimize->pageLoadedHandler(Object(HookEvent))
> #6 /is/htdocs/wp1172414_XTUVQZVTQ5/www/2014_webapp/wire/core/Wire.ph

**Comment by marvinscharle** [comment]
Hi Torsten,

sorry for misspelling your name the last time.

Another idea: can you please change line 334 to the following:

```
wire('db')->query("UPDATE " . self::table_name . " SET state = 0, reference = null, updated_at = $now WHERE reference = '$reference'");
```

**Comment by tobaco** [comment]
No problem with the name. I'm used to it … ;-)

Changing the line seems to do the trick!
At least there are no error messages anymore.

Danke!

**Comment by marvinscharle** [comment]
Thank you again for reporting this problem and helping me fix it.

ProcessImageMinimize has been updated to version 1.0.2 to address this issue.

As a reward for your help, we gift you 500 free image minimizations on minimize.pw. For this, please send me a message to minimize@conclurer.com with the mail address you registered at minimize.pw.

If you have any additional questions, feel free to contact me at any time.

Marvin

**Comment by tobaco** [comment]
fyi:

I suddenly just had the same error again on a client production site. there was no way to display anything on front- or backend.
the only fix i had, was to empty the process_image_minimize table.

out of curiosity: do you still develop and maintain this plugin/service? the last update was in 2014 so i wonder if you have abandoned this project or you think it's feature complete and needs no updates at this time. will it be compatible with ProcessWire 3?

thanks for all your hard work,
torsten
