### ISSUE TITLE
MySQL error on installation

### ISSUE THREAD

**Issue by marvinscharle** [conclurer/ProcessImageMinimize#5]
This error message appears while trying to install ProcessImageMinimize:

Unable to install module 'ProcessImageMinimize': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'USING BTREE' at line 2

**Comment by marvinscharle** [comment]
Requested:
- Version of ProcessImageMinimize
- Check the database for the process_image_minimize table and remove it if present
- Download the current version of ProcessImageMinimize and try to install it again

**Comment by benbyford** [comment]
- v1.0.2
- Table deleted
- tried install again on v1.0.2 = error: 
  Unable to install module 'ProcessImageMinimize': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'USING BTREE' at line 2

**Comment by marvinscharle** [comment]
Hi benbyford,

thank you for your report. Can you please tell me, what version your MySQL server has? 

Can you please remove the table again and run the following SQL statements by hand on your server:

```
CREATE TABLE process_image_minimize (image_id VARCHAR(255) NOT NULL PRIMARY KEY, reference VARCHAR(24), state INT(2) NOT NULL, processed VARCHAR(255), force_replace INT(1), created_at INT(11) UNSIGNED NOT NULL, updated_at INT(11) UNSIGNED NOT NULL);
CREATE UNIQUE INDEX minimize_api_reference ON process_image_minimize (reference) USING BTREE; 
CREATE INDEX minimize_api_state ON process_image_minimize (state) USING BTREE;
```

Can you tell me if these statements throw the same exceptions? 

Thanks in advance,

Marvin

**Comment by clipmagic** [comment]
I am getting the same error and dont know how to fix:

Unable to install module 'ProcessImageMinimize': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'USING BTREE' at line 2

Using PHP 5.5 and MYSQL 5.0.96

**Comment by marvinscharle** [comment]
Hi @clipmagic,

minimize.pw requires an InnoDB database table - depending on the mysql server configuration, your mysql server will create a database table using the MyISAM engine. Please make sure, that you use an InnoDB table.

Thanks,
Marvin

**Comment by clipmagic** [comment]
Hello Marvin

Thanks for your reply. I was able to resolve the issue. It was an old
version of MYSQL and it installed when I removed the USING BTREE statement
in both the indexing commands.

Regards

Prue Rowland
Clip Magic

p: +61 2 4351 8686
m: 0405 539 993
w: www.clipmagic.com.au http://www.clipmagic.com.au

From:  Marvin Scharle notifications@github.com
Reply-To:  conclurer/ProcessImageMinimize
<reply+003b34a0c24fef1d6202365a0223bdeb6774b6145872611e92cf00000001117b1a049
2a169ce021c56f7@reply.github.com>
Date:  Tuesday, 26 May 2015 3:12 am
To:  conclurer/ProcessImageMinimize
ProcessImageMinimize@noreply.github.com
Cc:  Prue Rowland admin@clipmagic.com.au
Subject:  Re: [ProcessImageMinimize] MySQL error on installation (#5)

Hi @clipmagic https://github.com/clipmagic ,

minimize.pw requires an InnoDB database table - depending on the mysql
server configuration, your mysql server will create a database table using
the MyISAM engine. Please make sure, that you use an InnoDB table.

Thanks,
Marvin


Reply to this email directly or view it on GitHub
<https://github.com/conclurer/ProcessImageMinimize/issues/5#issuecomment-105
271751> .
