### ISSUE TITLE
Database Error (Problem with PDO and mysqli)

### ISSUE THREAD

**Issue by philippreiner** [conclurer/ProcessImageMinimize#7]
ProcessWire 2.4 with a fresh installation of the module, produces the following error: 

Error: Exception: DB connect error 2002 - No such file or directory (in /home/(redacted)/wire/core/Database.php line 68)
#0 /home/(redacted)/wire/core/DatabaseMysqli.php(24): Database->__construct(Object(Config))
#1 /home/(redacted)/wire/core/DatabaseMysqli.php(34): DatabaseMysqli->db('query', 'method')
#2 /home/(redacted)/site/modules/ProcessImageMinimize/ProcessImageMinimize.module(237): DatabaseMysqli->__call('query', Array)
#3 /home/(redacted)/site/modules/ProcessImageMinimize/ProcessImageMinimize.module(237): DatabaseMysqli->query('SELECT image_id...')
#4 /home/(redacted)/site/modules/ProcessImageMinimize/ProcessImageMinimize.module(222): ProcessImageMinimize->pushToMinimizeQueue()
#5 /home/(redacted)/wire/core/Wire.php(381): ProcessImageMinimize->pageLoad

This error message was shown because you are logged in as a Superuser. Error has been logged.

This might be an issue with the usage of the old wire('db') call instead of the new PDO version wire('database').

**Comment by marvinscharle** [comment]
This is a known problem in PHP's mysqli library. 

Please make sure that you use **127.0.0.1** instead of **localhost** in your config.php to avoid connecting implicitly via socket to your local MySQL database server.

For more information, please check out: http://stackoverflow.com/a/8829005
